---
- name: Update the apt cache
  apt: update_cache=yes

- name: Upgrade current packages
  apt: upgrade=dist

- include: coreCli.yml
- include: keyboard.yml
- include: ui.yml
- include: userToAdmin.yml
